development:
  sessions:
    default:
      uri: 'mongodb://localhost:27017/cakes-dev'

test:
  sessions:
    default:
      uri: 'mongodb://localhost:27017/cakes-test'

<%
  unless ENV['VCAP_SERVICES'].nil?
    vcap_services = JSON.parse(ENV['VCAP_SERVICES'])
    uri = vcap_services['mongodb'].first['credentials']['uri']
%>

production:
  sessions:
    default:
      uri: <%= uri %>

<% end %>
